### PR TITLE
add Telegram Messenger

### LINKED ISSUE #40: Support telegram messenger
(I'll add a pull request when I have some time)

When clicking on a link in telegram it shows the following referrers:
- telegram web: `https://web.telegram.org/`
- Android app: `android-app://org.telegram.messenger`

### PR DESCRIPTION
**Pull request by Findus23**
fixes #40

### CODE REVIEW

**Comment by Findus23** [comment]
Does it work to use `android-app://org.telegram.messenger` or do I have to use only the "domain" `org.telegram.messenger`?

**Comment by sgiehl** [comment]
Guess `org.telegram.messenger` would be correct, as it compares "hostnames"

**Comment by sgiehl** [comment]
@Findus23 I'll merge this now. Would you add an icon if you didn't already?

**Comment by Findus23** [comment]
I'll do so next week and hope that the matomo-icons travis test notifies me as this is merged.

**Pull request merged**
