### PR TITLE
Added Peepeth to Socials.yml

### PR DESCRIPTION
**Pull request by LeslieOA**
[Peepeth](http://peepeth.com/) is a decentralised "Twitter-like" social media feed that's gaining users.

### CODE REVIEW

**Comment by Findus23** [comment]
If it is decentralized, would it make sense to add the URLs of some of the larger instances (assuming it works similar to the fediverse/Mastodon)?

**Comment by LeslieOA** [comment]
@Findus23 It's "decentralised" as in it uses the Ethereum blockchain (and I believe IPFS for some or all resources). 
See [About Peepeth](https://peepeth.com/about) and let me know what you think.

**Comment by LeslieOA** [comment]
@Findus23 Just seen your update. Thanks. Slightly related question: how long does it usually take for this sort of thing to end up in Matomo Cloud, or is it a API/feed that Cloud and Community consume?

**Comment by sgiehl** [comment]
The searchengines and social networks definitions from this repo are pulled weekly from each matomo instance (if a connection can be established). Not sure how it is configured on cloud, but I assume it should be the same.

**Pull request merged**
