### PR TITLE
Add pinterest.pl domain

### PR DESCRIPTION
**Pull request by Sija**
SSIA

### CODE REVIEW

**Comment by sgiehl** [comment]
Hm... That domain does endless redirects and doesn't show pinterest at all

**Comment by Sija** [comment]
It does work, I can assure you.

**Comment by sgiehl** [comment]
I always get redirect to another advertising site

**Comment by Findus23** [comment]
I am not sure if this is an official URL. Whois shows another company

```
$ whois pinterest.pl
[Querying whois.iana.org:43 'pinterest.pl']
[Redirected to whois.dns.pl]
[Querying whois.dns.pl:43 'pinterest.pl']
[whois.dns.pl]

DOMAIN NAME:           pinterest.pl
registrant type:       individual
nameservers:           ns1.premium.pl.
                       ns2.premium.pl.
created:               2011.10.27 16:18:31
last modified:         2018.04.28 11:37:35
renewal date:          2018.10.27 17:18:31

no option

dnssec:                Unsigned


REGISTRAR:
premium.pl Sp. z o.o.
Zbożowa 4
70-653 Szczecin
801 066 444
pomoc@premium.pl
https://premium.pl/kontakt

WHOIS database responses: http://www.dns.pl/english/opiskomunikatow_en.html

WHOIS displays data with a delay not exceeding 15 minutes in relation to the .pl Registry system
Registrant data available at http://dns.pl/cgi-bin/en_whois.pl
```

**Comment by Sija** [comment]
Damn, that's correct! You're so right, and I was wrong, twice... I'm so ashamed 😓 I shouldn't do PRs l8 at night, damn...

**Comment by Sija** [comment]
Thanks for vigilance guys!

**Pull request closed without merging**
