### PR TITLE
Npm package json

### LINKED ISSUE #43: Add package.json to make the repo compliant with NPM
Hi there!
I am quite interested into using your lists into a node.js app.
Would you like I do a PR the appropriate package.json file?
Right now, I need to rely on [Napa](https://github.com/shama/napa) to download it.

### PR DESCRIPTION
**Pull request by boris-hocde**
Fixes #43 
I left the version to 1.4.1
Need an update here if you merge & tag master :)

### CODE REVIEW

**Comment by sgiehl** [comment]
@Findus23  could you confirm that this package.json is fine?

**Comment by sgiehl** [comment]
Sure, feel free to publish

**Comment by Findus23** [comment]
[Done](https://www.npmjs.com/package/searchengine-and-social-list)

It can be installed with `npm install searchengine-and-social-list`.

**Comment by boris-hocde** [comment]
Thanks guys! You rock :)

**Pull request merged**
