### PR TITLE
Add Mastodon as social network

### PR DESCRIPTION
**Pull request by mattab**

### CODE REVIEW

**Comment by Findus23** [comment]
obviously this will only work with users of mastodon.social (which is a fraction of Mastodon users), but it's better than nothing.

**Comment by sgiehl** [comment]
@Findus23  I've added a bunch of additional URLs that are running Mastodon. If you know more, feel free to add them

**Comment by mattab** [comment]
FYI @Findus23 @sgiehl there are some more on here https://joinmastodon.org/#getting-started

**Comment by Findus23** [comment]
I went through the list of hosts that are connected to my instance with the most known user accounts.
The following are on top (in addition to the existing ones):
```
- chaos.social
- mastodon.art
- social.tchncs.de
- cybre.space
- vis.social
```
I'd say those are enough for now.

**Comment by sgiehl** [comment]
@Findus23 I've added them to the list. Will merge that now. Would you mind adding an icon to the icons repo?

**Pull request merged**
